Chore/tailwind configuration
depromeet/pingpong-client pull request #17
Opened 2022-11-08 02:32 UTC by L2HYUNN

## What's Changed? 
tailwind 설정을 위한 파일 추가

## Screenshots
commit 내역 참고

## Related to any issues?
- #16  

## Dependency Changes
```
"autoprefixer": "10.4.13",
"postcss": "8.4.18",
```

## Test Code
- ⛔️

2022-11-08 02:39 UTC, L2HYUNN commented
@doyoonear @hwangyena 
local에서 tailwind 적용을 확인했습니다~!
문제 없다면 merge후 개인 local 브런치에서 연습 및 작업 진행하겠습니다 :)

2022-11-10 12:20 UTC, hwangyena requested changes

2022-11-10 12:20 UTC, hwangyena commented on postcss.config.js
> +module.exports = {
혹시 postcss는 연습용으로 넣으신걸까요~?

2022-11-10 14:43 UTC, L2HYUNN commented on postcss.config.js
> +module.exports = {
앗 아니요 tailwind nextjs 문서 참고해서 설치할때 똑같이 따라해서 설치한 부분인데 자세히 찾아보니 css 파일 사용하지 않으면 제거해도 될 거 같네요! 이 부분 수정해보겠습니다~!

2022-11-10 17:04 UTC, L2HYUNN commented
postcss, autoprefixer 관련해서 참고한 자료들 추가합니다~!

기본적인 진행은 tailwind 공식 문서 참고하였습니다. 
[Install Tailwind CSS with Next.js](https://tailwindcss.com/docs/guides/nextjs) 

해당 문서에서는 postcss를 이용한 설치 및 설정 방법을 알려주고 있습니다.

하지만 아래의 문서에서는 tailwind에 반드시 preprocessor를 사용할 필요는 없다고 이야기 하고 있으며 사용하게 된다면 postcss 사용을 권장하고 있습니다.
[Using with Preprocessors](https://tailwindcss.com/docs/using-with-preprocessors)

2022-11-14 02:09 UTC, L2HYUNN commented
@doyoonear @hwangyena 
postcss, autoprefixer 제거이후 CLI 사용해보았는데 아무래도 css 변경시마다 build process를 다시 진행해줘야하는 거 같습니다..

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/79739512/201559496-85032b11-3985-4cc1-bde5-4c17cb5f1184.png">

실제로 프로젝트에서 다음과 같이 적용해보았는데요, component 내에서 className을 새로 작성할 시에 다음과 같은 명령어를 다시 실행해 build process를 진행해야하는 거 같습니다.

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/79739512/201559611-518d39e2-fee2-4518-bdcc-c25dc58eea99.png">

eslint plugin처럼 저장시에 자동으로 build를 진행해주지 않으면 실사용이 어려워보이고 이렇게 해서 적용한다고 해도 상당히 번거로워 보입니다. 

또한 yarn remove postcss autoprefixer 이후에 다음과 같은 오류가 발생하고 있습니다. TS Restart를 통해 임시로 해결해도 다시 문제가 발생하는 걸로 보아 아래와 같은 방법( yarn dlx @yarnpkg/sdks vscode )을 통해 해결을 시도해야할 거 같은데.. 고민중에 있습니다.
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/79739512/201560148-785eeb1e-28e4-4f4d-9197-b562dd259ab4.png">
<img width="777" alt="image" src="https://user-images.githubusercontent.com/79739512/201560177-5ca9f7f8-13ae-487d-8228-bf306a296d9b.png">

참고 자료:
1. [Installation Tailwind CLI](https://tailwindcss.com/docs/installation)
2. [Setup Tailwind CSS in 20 seconds without node_modules](https://dev.to/tomaszbujnowicz/setup-tailwind-css-in-20-seconds-without-nodemodules-1b83)
3. [Cannot find module 'next' or its corresponding type declarations](https://stackoverflow.com/questions/69238794/cannot-find-module-next-or-its-corresponding-type-declarations)

2022-11-15 02:45 UTC, doyoonear commented
허.. 일단 공유해주신 내용만 봤을때는 사용하기가 너무 어려워보이는데, 작업 우선 진행하려면 일단 최초에 올려주셨던 postcss, autoprefixer 사용한 방법으로 세팅해놓고 이후에 가능할때 postcss, autoprefixer 제거하는방향으로 해야할것같습니다! 
어제 작성해주신 코멘트 이슈로 남겨놓고 이 PR은 우선 머지하는게 좋을것같아요
cc. @hwangyena

2022-11-15 02:45 UTC, doyoonear approved these changes

2022-11-15 04:41 UTC, hwangyena commented
저도 방금 세팅을 해봤는데, next.js + tailwindcss + postcss 를 사용하는 것이 좋을 것 같습니다.

다만 우려되는 점은 현재 설치되어 있는 css 관련 툴이 너무 많다는 것인데요..
저희가 처음에 논의했을때는 tailwindcss + styled-component 였는데, 찾아보니 그렇게 사용하기보단 
1. tailwindcss + postcss + (scss 등의 전처리기)
2. styled-component
3. 1+2의 방식을 혼합한  [twin.macro](https://maxrozen.com/using-tailwind-css-in-react-css-in-js)
방식으로 사용하더라구요.
생각해보니 tailwind와 css in JS 방식을 혼합해서 사용하는 경우에, 코드 파편화가 발생할 것 같습니다.
그래서 저희도 1~3 방법중에 하나로 통일하는 것은 어떨까요?

저는 개인적으로 [이 블로그](https://daily.dev/blog/why-i-moved-from-styled-components-to-tailwind-css-and-whats-the-future-of-css-in-js)를 읽었을때 1번의 방법이 가장 좋은것 같아 보이는데 다른 분들 의견이 궁금합니다.
두 개의 장단점 및 비교분석은 [이곳](https://xpromx.me/blog/tailwinds-vs-styled-components)을 참고하시면 좋을 것 같습니다.

cc. @L2HYUNN @doyoonear

2022-11-15 09:51 UTC, doyoonear commented
예나님이 공유해주신 방향 이해했습니다! 그런데 아무래도 동현님과 제가 아직 tailwind 에 익숙하지 않다보니 테일윈드만 단독으로 사용했을때 개발속도가 더딜것 같다는 생각이 듭니다. 

그래서  어쩔수없이 스타일 코드가 다소 혼재되더라도 함께 사용하고 이후에 코드를 개선하는 방향으로 하면어떨까요?? 

스타일드컴포넌트+테일윈드 조합을 쓸때는 twin.macro 를 쓰면 편하고 코드정리도 잘된다고 들었는데 예전에 적용하려다가 next에 적용 못하고 실패했었던 경험이 있어서.. 적용가능하면 3번이 제일 좋지 않을까 싶습니다! 아니면 일단 같이 사용하는 방향으로 제작하고 이후 리팩토링하는게 좋을것같습니다

2022-11-15 15:36 UTC, merged