Feat: tag 컴포넌트 추가
depromeet/pingpong-client pull request #42
Opened 2022-11-20 05:10 UTC by doyoonear

## What's Changed? 
- 태그 컴포넌트 추가
- tagStyle props에 따라 3가지 스타일로 나뉩니다. 
- 글자만 표시하는  컴포넌트로 일단 클릭 시 동작은 따로 없습니다. 

```
<Tag tagStyle="dark" />
<Tag tagStyle="medium" />
<Tag tagStyle="light" />
```
### tailwind variable fix
```
10: '10rem' -> 10: '1rem',
```

## Screenshots
<img width="300" alt="Screen Shot 2022-11-20 at 2 05 34 PM" src="https://user-images.githubusercontent.com/46391618/202886572-2b1cec14-31db-4311-af02-0ea8976c614b.png">
<img width="300" alt="Screen Shot 2022-11-20 at 2 05 46 PM" src="https://user-images.githubusercontent.com/46391618/202886568-eb77fb9f-f7a6-455d-bec9-3c21efbe9a6f.png">
<img width="300" alt="Screen Shot 2022-11-20 at 2 05 40 PM" src="https://user-images.githubusercontent.com/46391618/202886570-baa9c138-4559-4e02-b44a-2e6af345ca78.png">

## Related to any issues?
- ⛔️

## Dependency Changes
- ⛔️

## Test Code
- ⛔️

2022-11-20 06:30 UTC, L2HYUNN approved these changes
LGTM

2022-11-20 06:30 UTC, L2HYUNN commented on src/components/common/Tag.tsx
> +};
```suggestion
interface StyleProps {
  [color: string]: string;
}

const styleClass: StyleProps = {
  dark: 'text-white bg-gray-500',
  medium: 'text-gray-500 bg-gray-200',
  light: 'text-gray-500 bg-white border border-gray-200',
  default: 'text-b4 px-10 py-4 rounded-full',
};

const Tag = ({ tagStyle = 'dark', children }: PropsWithChildren<TagProps>) => {
  return (
    <div className="flex">
      <div className={`${styleClass[tagStyle]} ${styleClass['default']}`}>{children}</div>
    </div>
  );
};
```

style class를 react component 외부에서 관리하고 styleClass를 얻기위한 함수 및 반복문을 제거하기 위해서 obj을 사용해봤습니다!

2022-11-20 12:07 UTC, hwangyena requested changes

2022-11-20 12:07 UTC, hwangyena commented on src/components/common/Tag.tsx
> +  tagStyle?: string;
string 보다, 'dark' | 'medium' | 'light'로 하면 타입추론이 더 명확해질 것 같습니다~!!

2022-11-20 12:07 UTC, hwangyena commented on src/components/common/Tag.tsx
> +};
typeof 사용하시면 추론 가능할거예요!

2022-11-20 15:04 UTC, doyoonear commented on src/components/common/Tag.tsx
> +};
type enum 사용해서 상수로 관리하면 될것 같습니다! 

이전에 사용할때 이렇게 많이 적용했어서, 아래와 같은식으로 적용해보도록하겠습니다! 

```
const TagStyleType = {
  LIGHT: 'LIGHT',
  MEDIUM: 'MEDIUM',
  DARK: 'DARK',
} as const;
```

2022-11-21 14:40 UTC, doyoonear commented on src/components/common/Tag.tsx
> +  tagStyle?: string;
타입 상수 사용하여 수정했습니다!
https://github.com/depromeet/pingpong-client/pull/42/commits/79aaa3e3d3a488166d1b8aeb727e3f53aa6830c4
https://github.com/depromeet/pingpong-client/pull/42/commits/66b74aef36f51da0936f26ea2cb6f10fbd2f0f1e

2022-11-21 14:40 UTC, doyoonear commented on src/components/common/Tag.tsx
> +};
타입 상수 사용하여 수정했습니다!
https://github.com/depromeet/pingpong-client/pull/42/commits/79aaa3e3d3a488166d1b8aeb727e3f53aa6830c4
https://github.com/depromeet/pingpong-client/pull/42/commits/66b74aef36f51da0936f26ea2cb6f10fbd2f0f1e

2022-11-22 14:52 UTC, hwangyena approved these changes
LGTM

2022-11-22 14:55 UTC, hwangyena requested changes

2022-11-22 14:55 UTC, hwangyena commented on package.json
> +    "tsconfig-paths-webpack-plugin": "^4.0.0",
도윤님 혹시 이부분 왜 설치하신건가요??

2022-11-26 06:22 UTC, hwangyena approved these changes
LGTM

2022-11-26 06:27 UTC, merged