Feat: bottom sheet 컴포넌트
depromeet/pingpong-client pull request #45
Opened 2022-11-20 14:33 UTC by doyoonear

## What's Changed? 
### Portal 컴포넌트 추가
- Portal 을 사용해서, Bottomsheet 컴포넌트가 열리게 합니다. 
- 이후 popup 컴포넌트에도 사용할 수 있을것 같습니다.
- Portal 컴포넌트로 감싸고, isShowing boolean 값으로 컨트롤합니다.

```
<Portal isShowing={isShowing}>
      <ChildrenComponent />
</Portal>
```

### bottom sheet 바텀시트 컴포넌트 추가 
- bottom sheet 바텀시트 컴포넌트 추가
- bottomsheet 내부에 들어가는 optionlist 컴포넌트 추가

### 설정 변경
- styled-components 를 사용 시에 next dev 의 HMR 정상 동작하지 않는 이슈가 있어서 next.config.js 수정

## Screenshots
<img width="486" alt="Screen Shot 2022-11-20 at 11 17 37 PM" src="https://user-images.githubusercontent.com/46391618/202907283-7034f265-f1d0-49a6-9742-332e7fe8490a.png">

## Related to any issues?
- ⛔️

## Dependency Changes
```
"@types/styled-components": "^5.1.26",
```

## Test Code
- ⛔️

2022-11-21 03:17 UTC, L2HYUNN approved these changes
좋은 코드 잘 봤습니다!! 빠르게 merge하고 한 번 사용해보고 싶네요 ㅎㅎ 고생하셨습니다 :)

2022-11-21 03:17 UTC, L2HYUNN commented on src/components/common/Portal.tsx
> +  if (!isMounted || !container) return <></>;
```javascript
return (isMounted & container) ? createPortal(<div>{isShowing && children}</div>, container) : <></>
```
조건문의 ```!```연산자는 가독성을 떨어트리는 부분이 있는거 같아 변경해보았고
삼항 연산자를 이용하여 return문 하나로 통합해보았습니다!

2022-11-21 03:17 UTC, L2HYUNN commented on src/store/bottomSheet.ts
> +});
저 같은 경우 store 폴더 구조와 네이밍을 다음과 같이 가져갔습니다!

atom의 경우 recoil hook의 parameter에서만 사용되기 때문에 다음과 같은 이름도 괜찮다고 생각했습니다~!

도윤님처럼 사용하는 방식도 좋아보여서 하나로 통일하면 좋을 것 같습니다!!

<img width="312" alt="image" src="https://user-images.githubusercontent.com/79739512/202955269-effea631-b0a4-4003-b863-3bc9a97bf902.png">
<img width="458" alt="image" src="https://user-images.githubusercontent.com/79739512/202955308-2411862a-e8bc-40f3-a021-f9a3014c13e1.png">

- #32

2022-11-21 13:52 UTC, hwangyena commented on src/components/common/BottomSheet.tsx
> +  const onDeleteHandler = (e: React.MouseEvent<HTMLDivElement>) => {
저희 naming이 props로 사용되는 경우 onXXX, 함수 내부적에서만 동작하는 경우 handleXXX 였던 것으로 기억합니다!

2022-11-21 13:52 UTC, hwangyena commented on src/hooks/useBottomSheet.ts
> +    setIsShowing,
recoil도 불변성 유지를 위해 함수를 따로 빼서 관리하는 것으로 알고있는데, setIsShowing보다 함수내에서 관리하는 것이 어떨까요?

2022-11-21 13:52 UTC, hwangyena commented on src/components/common/BottomSheet.tsx
> +export default function BottomSheet({ isShowing, children, handleClose }: BottomSheetProps) {
memo가 필요해보입니다!

2022-11-23 03:04 UTC, doyoonear commented on src/hooks/useBottomSheet.ts
> +    setIsShowing,
hook 바깥에서는 isShowing을 변경 불가능하게 하는 방향을 말씀해주신거죠?

2022-11-26 06:26 UTC, hwangyena requested changes

2022-11-26 06:26 UTC, hwangyena commented on src/store/bottomSheet.ts
> +export const bottomSheetOpenState = atom({
이부분 도현님 코드처럼 변경이 필요해요~~

2022-11-26 06:35 UTC, doyoonear commented on src/store/bottomSheet.ts
> +export const bottomSheetOpenState = atom({
반영했습니다~! https://github.com/depromeet/pingpong-client/pull/45/commits/6af689b1a8f949a49a71ca10bacf19a2cd7e11bd

2022-11-26 06:52 UTC, hwangyena approved these changes
LGTM

2022-11-26 06:54 UTC, merged